# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e1bbc4d4e29e3f31878ca1d1d3e17ed436d295cebfb07b55a3a2a398c619692ba04fe5f1834b51b2b93d4c46a4dc7661bb45526c87588148095615ac05a5e97

test:
  secret_key_base: c18538e87f2f5e1c9a6413575872a165c8266f44abdc3f7a474f727d420ccbaeafe56bd16d93c6d50bab6725dbc13779cb73e110786f69b743117c682cbd2b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
